### ISSUE TITLE
Symbol and MLN representation

### ISSUE THREAD

**Issue by hpoit** [hpoit/Kenya.jl#2]
Hello @tawheeler, @mykelk, @sbromberger, and @abhijithch. Right now this is what I have to represent

![image](https://cloud.githubusercontent.com/assets/3711100/17932769/eb1611e0-69e7-11e6-82b8-92c935cd6e95.png)
![image](https://cloud.githubusercontent.com/assets/3711100/17932802/15d51eee-69e8-11e6-9fba-85da2eb73f98.png)

Source http://homes.cs.washington.edu/~pedrod/papers/mlj05.pdf

I would appreciate some help getting started with LightGraphs.jl. Will read thoroughly about it now.

**Comment by sbromberger** [comment]
Frankly, this doesn't look like a straightforward application of either, LightGraphs or Graphs.jl. For LightGraphs, you'd need to store the node->variable information in a map of some sort, which is not memory efficient, and then you'd have to figure out how to label the cliques and map the potential functions to each. I don't know what the state of first-order functions is in Julia these days, but in the old days this would probably be very inefficient.

I can't speak to Graphs.jl, but my (very limited) experience with it suggests you might have similar issues with respect to the potential functions. It can handle the vertex mapping much better than LG since it doesn't really care what type of object you use to represent vertices.

**Comment by hpoit** [comment]
@sbromberger, I am trying to make sense between your comment and these sections of the [Tuffy manual](http://i.stanford.edu/hazy/tuffy/doc/tuffy-manual.pdf)

![image](https://cloud.githubusercontent.com/assets/3711100/17935112/8bae9188-69f0-11e6-89c2-c7cc41921175.png)

![image](https://cloud.githubusercontent.com/assets/3711100/17935223/e8c30a70-69f0-11e6-851c-96cb1be05a9c.png)

![image](https://cloud.githubusercontent.com/assets/3711100/17935689/a56db6ce-69f2-11e6-9dc9-e877659e7601.png)

![image](https://cloud.githubusercontent.com/assets/3711100/17935792/efb29e98-69f2-11e6-803a-5ce1b3366b5d.png)

![image](https://cloud.githubusercontent.com/assets/3711100/17935854/2c9fede2-69f3-11e6-8429-da5327cf75ac.png)

![image](https://cloud.githubusercontent.com/assets/3711100/17935953/92007e9a-69f3-11e6-8090-c5bbe35f742c.png)

**Comment by hpoit** [comment]
I also found these parts on MLN from [Helene's paper](https://hal.inria.fr/file/index/docid/820383/filename/PapadopoulosTzanetakis_MLN_ICASSP_2013.pdf) useful, but not complete

![image](https://cloud.githubusercontent.com/assets/3711100/17936278/a2b013e4-69f4-11e6-9a82-1a9bcc96af37.png)
![image](https://cloud.githubusercontent.com/assets/3711100/17936404/1367ca5a-69f5-11e6-8ff0-b32a009ff7af.png)

**Comment by tawheeler** [comment]
You almost need to write a compiler!
I actually wrote a very non-professional implementation of log-linear models + training for a paper. I had the very issues that @sbromberger mentioned.  Feel free to check out [this repo](https://github.com/sisl/2016_itsc_scenegen) and/or read [the paper](http://timallanwheeler.com/aboutme/papers/wheeler2016factorgraph.pdf).

**Comment by hpoit** [comment]
@tawheeler that's a kickass paper, will take it in tonight, thanks.

@sbromberger thanks for the input, could you expand on first-order logic in Julia? I couldn't find a package like http://stackoverflow.com/questions/2304726/first-order-logic-engine for Python or the Markov Logic option from Tweety in Java http://tweetyproject.org/lib/index.html Should these be present even with a graphs package? I will look into the mapping of potentials efficiency issue, thank you!

**Comment by sbromberger** [comment]
not first-order logic, first-order functions. The issue is (was?) that passing functions as arguments to other functions is very inefficient in Julia. This may have changed recently; I haven't been following developments. See https://github.com/timholy/FastAnonymous.jl for more details.

**Comment by hpoit** [comment]
Thanks @sbromberger. Sorry for the mistake.

**Comment by hpoit** [comment]
@sbromberger, from FastAnonymous.jl, 
`# Full manual inlining`
`@time test_inlined(1)`
`julia> @time test_inlined(10^7)`
`elapsed time: 0.078703981 seconds (112 bytes allocated)`
`2.973333503333424e7`
seems efficient, but efficient enough?

**Comment by hpoit** [comment]
@tawheeler, so you efficiently mapped the potentials with a Gaussian prior over the log-linear parameters θ, using SGA and momentum to speed up learning? Are the types of objects to represent vertices an efficiency issue? 

Can you expand on 'you almost need to write a compiler'? I will if that's what it takes to do it correctly.

**Comment by tawheeler** [comment]
[Factor.jl](https://github.com/sisl/2016_itsc_scenegen/blob/master/src/factor.jl) contains the factor functions. I avoided using first-order functions and made types instead. Nevertheless, this led to issues when iterating over vectors of these types, as these vectors were necessarily abstract. See [here](https://groups.google.com/forum/#!searchin/julia-users/wheeler%7Csort:relevance/julia-users/OBs0fmNmjCU/sZQIAtkkAAAJ). I ended up hacking it using explicit `if` statements to get it to run fast.

In the cast of MLNs you won't have a small explicit set of factors, but will want to support a large, general set. If each vertex stores a first-order function you will end up with type instability. Julia 0.4 doesn't have a way to enforce return types, so there will be memory allocation and error checking in every call to the first-order functions. There may be a workaround as of Julia 0.5.

I mention compiling because you will likely need to parse input files like in the examples you posted above. `!hasWord(d, NICE) v review (d, POS)` would have to be interpreted and then parsed into a representation the MLN can understand. I suppose compiling isn't the right word - really just lexing and parsing. This process builds the symbol tables they mention.

**Comment by hpoit** [comment]
Thanks Tim. Could I maybe work the first-order functions with `if` statements and `typeassert` to avoid type instability? Thanks for expanding on the compiling issue, it sets the work to be done. Is JuliaParser.jl the way? 

Hi @johnmyleswhite, I am reading the [book-long thread on return types](https://github.com/JuliaLang/julia/issues/1090#issuecomment-144538070), and since you summarized it so well, would you have any suggestions on keeping the mapping of first-order harmonic functions type-stable?

@StefanKarpinski and @JeffBezanson, your suggestions are also welcome.

**Comment by hpoit** [comment]
I am trying to figure out how to reduce the options to calculations

**Comment by hpoit** [comment]
Hello @jongwook, have you read this? https://hal.inria.fr/file/index/docid/820383/filename/PapadopoulosTzanetakis_MLN_ICASSP_2013.pdf

**Comment by jongwook** [comment]
Hi @hpoit, unfortunately no, I'm not very experienced with MLNs.

**Comment by hpoit** [comment]
Hello @dpsanders, MLN can learn from all your research interests. I am taking in all I can on Julia, including your very complete and explicit Julia material, to get this repo started. I am trying to build a flight plan first to figure out how much time I will need to get it done. Suggestions are welcome. Cheers.

**Comment by hpoit** [comment]
This is fine if a named function effecting the transform one wants already exists to pass as the first argument to map(). Often, however, a ready-to-use, named function does not exist. In these situations, the anonymous function construct allows easy creation of a single-use function object without needing a name:

```
julia> map(x -> x^2 + 2x - 1, [1,3,-1])
3-element Array{Int64,1}:
  2
 14
 -2
```

**Comment by hpoit** [comment]
![image](https://cloud.githubusercontent.com/assets/3711100/18098405/76a7cd82-6eb8-11e6-90d6-d57fffee3154.png)

**Comment by hpoit** [comment]
[Further Reading](http://docs.julialang.org/en/release-0.4/manual/functions/#further-reading)

We should mention here that this is far from a complete picture of defining functions. Julia has a sophisticated type system and allows multiple dispatch on argument types. None of the examples given here provide any type annotations on their arguments, meaning that they are applicable to all types of arguments. The type system is described in [Types](http://docs.julialang.org/en/release-0.4/manual/types/#man-types) and defining a function in terms of methods chosen by multiple dispatch on run-time argument types is described in [Methods](http://docs.julialang.org/en/release-0.4/manual/methods/#man-methods).

**Comment by hpoit** [comment]
@sbromberger, label inference may solve the problem for cliques, will check. 

For mapping variables of parents to nodes, instead of a table specifying the node's conditional probability for every state of its parents, a simpler distribution can be learned. The most popular choice is a probabilistic version of the logical OR operation, i.e. any cause alone can provoke an effect, with each cause having a certain probability of failing to do so. [Heckerman](http://research.microsoft.com/en-us/um/people/heckerman/) and others have learned Bayesian nets that diagnose hundreds of infectious diseases this way. Google uses this type of BN in Adsense to learn from one hundred billion text snippets and search queries. 

Now I still have to research on how to solve type stability.

**Comment by hpoit** [comment]
Hi @emoszkowski, I wonder what results you would get if you applied first-order logic to DSGE. Check this out https://github.com/sisl/BayesNets.jl/issues/29

**Comment by hpoit** [comment]
@emoszkowski, I am wondering if I should use `struct`s the way you have for every function call?

**Comment by hpoit** [comment]
Hi @nassarhuda! I am just exploring the possibilities in Julia, and am watching your JuliaCon video. Could MatrixNetworks.jl represent the graphical part of Kenya.jl? Thanks!

**Comment by hpoit** [comment]
@nassarhuda, is network alignment more efficient than structure mapping? 
https://groups.google.com/d/msg/julia-users/a8rObcwXT_c/COBSlWxXBgAJ

**Comment by hpoit** [comment]
Hi @tawheeler, how does this look?

MLN program syntax: 

(cat is category, p is paper, c1 is category 1, c2 is category 2)

source code: cat(p,c1),cat(p,c2)=> c1=c2

Lexical analysis (token stream): cat ( p , c1 ) , cat ( p , c2 ) => c1 = c2

Syntax analysis/parsing (AST): 
if cat(p,c1)==cat(p,c2) then c1=c2

decorated AST: 
if UInt cat (UInt p, UInt c1) Boolean == UInt cat (UInt p, UInt c2) then UInt c1 UInt = UInt c2

I am looking to JuliaParser.jl now and when defining the src function should I define a table of token variables first (cat, p, c1, c2)? 

You recommended I start with a graph in LightGraphs - isn't that after lex, parsing, semantics is done? There's a whole other step for semantics after parsing here

MLN semantics: schema, domain, formula in clausal form with weights, new ground clause for a probability distribution over possible worlds (deterministic databases), cost of worlds for a prob. dist. over all instances (lowest cost, most likely world).

**Comment by hpoit** [comment]
When you mentioned compiling, I think it was the right word http://www.cs.cornell.edu/courses/cs412/2008sp/lectures/lec12.pdf

**Comment by hpoit** [comment]
I'm sorry, by token variables I think I meant arguments.

**Comment by hpoit** [comment]
Also, from this [thread](https://groups.google.com/forum/#!searchin/julia-users/parser%7Csort:relevance/julia-users/rxUtcvCT2lI/tO9hd2jiBwAJ), I am thinking whether I should completely insulate users from writing strings, but instead, symbols and expressions only.
